config/routes.rb
Rails.application.routes.draw do
  root to: "competitions#index"
  
  devise_for :users
  resources :languages
  resources :problems
  resources :competitions

end

app/models/competition.rb
class Competition < ActiveRecord::Base
    
    validates_presence_of :title
    validates_presence_of :location
    validates_presence_of :website
    validates_presence_of :year
    validates_presence_of :remote_server
    validates_presence_of :remote_user
    validates_presence_of :begin_time
    validates_presence_of :blind_time
    validates_presence_of :end_time
    
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :competition
  
  validates_presence_of :code
  validates_presence_of :description
  validates_presence_of :competition
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:title, :location, :website, :year, :remote_server, :remote_user, :begin_time, :blind_time, :end_time)
    end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:name)
    end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
  end

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html { render :new }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem.destroy
    respond_to do |format|
      format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:code, :description, :competition_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :remote_server %><br>
    <%= f.text_field :remote_server %>
  </div>
  <div class="field">
    <%= f.label :remote_user %><br>
    <%= f.text_field :remote_user %>
  </div>
  <div class="field">
    <%= f.label :begin_time %><br>
    <%= f.datetime_select :begin_time %>
  </div>
  <div class="field">
    <%= f.label :blind_time %><br>
    <%= f.datetime_select :blind_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Competitions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Website</th>
      <th>Year</th>
      <th>Remote server</th>
      <th>Remote user</th>
      <th>Begin time</th>
      <th>Blind time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.title %></td>
        <td><%= competition.location %></td>
        <td><%= competition.website %></td>
        <td><%= competition.year %></td>
        <td><%= competition.remote_server %></td>
        <td><%= competition.remote_user %></td>
        <td><%= competition.begin_time %></td>
        <td><%= competition.blind_time %></td>
        <td><%= competition.end_time %></td>
        <td><%= link_to 'Show', competition %></td>
        <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
        <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competition', new_competition_path %>

app/views/competitions/new.html.erb
<h1>New Competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @competition.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @competition.location %>
</p>

<p>
  <strong>Website:</strong>
  <%= @competition.website %>
</p>

<p>
  <strong>Year:</strong>
  <%= @competition.year %>
</p>

<p>
  <strong>Remote server:</strong>
  <%= @competition.remote_server %>
</p>

<p>
  <strong>Remote user:</strong>
  <%= @competition.remote_user %>
</p>

<p>
  <strong>Begin time:</strong>
  <%= @competition.begin_time %>
</p>

<p>
  <strong>Blind time:</strong>
  <%= @competition.blind_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @competition.end_time %>
</p>

<%= link_to 'Edit', edit_competition_path(@competition) %> |
<%= link_to 'Back', competitions_path %>

app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
  <% if @language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% @language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing Language</h1>

<%= render 'form' %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Languages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.name %></td>
        <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Edit', edit_language_path(language) %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<h1>New Language</h1>

<%= render 'form' %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>

<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <h1>oi</h1>

<%= yield %>

  <h1>tchau</h1>

</body>
</html>

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label "Competition" %><br>
    <%#= f.text_field :competition_id %>
    <%= f.select :competition_id, options_for_select(Competition.all.map{|p|[p.title, p.id]} ) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Problems</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Competition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= problem.code %></td>
        <td><%= problem.description %></td>
        <td><%= link_to problem.competition.title, problem.competition %></td>
        <td><%= link_to 'Show', problem %></td>
        <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
        <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/new.html.erb
<h1>New Problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @problem.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @problem.description %>
</p>

<p>
  <strong>Competition:</strong>
  <%= @problem.competition %>
</p>

<%= link_to 'Edit', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %>